import esbuild from 'esbuild';
import process from 'process';
import fs from 'fs';
import path from 'path';
import { builtinModules } from 'module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view/edit the source, it lives under src/ — see ARCHITECTURE.md for the module map.
*/
`;

const prod = process.argv[2] === 'production';

// getSpriteUrl()/villageMapUrl in src/core/plugin.ts resolve character art and the village map
// from the PLUGIN ROOT (alongside main.js) — that's where Obsidian's adapter.getResourcePath
// can actually reach them at runtime, not from src/. esbuild only bundles .ts/.js; these image
// assets need an explicit copy on every build, or the sprites 404 and every villager silently
// falls back to its bare profession-emoji badge.
function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (entry.name.startsWith('.trashed-')) continue;
    const from = path.join(src, entry.name);
    const to = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(from, to);
    else fs.copyFileSync(from, to);
  }
}
function copyStaticAssets() {
  // src/assets/characters/roster/<Name>/<direction>.png -> characters/<Name>/<direction>.png
  const spriteSrc = path.join('src', 'assets', 'characters', 'roster');
  if (fs.existsSync(spriteSrc)) copyDir(spriteSrc, 'characters');
  // src/village/village-map.jpg -> village-map.jpg
  const mapSrc = path.join('src', 'village', 'village-map.jpg');
  if (fs.existsSync(mapSrc)) fs.copyFileSync(mapSrc, 'village-map.jpg');
}
copyStaticAssets();

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/core/plugin.js'],
  bundle: true,
  // obsidian, electron, and CodeMirror are provided by the Obsidian app itself at runtime —
  // bundling them in would be wrong (and mostly wouldn't work); Node builtins are excluded too
  // since this runs inside Obsidian's Electron/Node context, not a browser.
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  outfile: 'main.js',
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
